In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model
import seaborn as sns


sns.set()

In [2]:
df = pd.read_csv('data.csv')

In [3]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

## Bedrooms column has missing data, take median of the column data where present and apply on missing values

In [5]:
bedrooms_median=df.bedrooms.median()
df['bedrooms']=df.bedrooms.fillna(bedrooms_median)

In [6]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.5   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

## Building model using sklearn linear regression, fit and predict

In [7]:
linear_reg=linear_model.LinearRegression()
linear_reg.fit(df[['area', 'bedrooms', 'age']], df[['price']])

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

## Training is over, predicting...

In [8]:
linear_reg.coef_

array([[    198.47159002, -116583.73881651,  -14267.77585936]])

In [9]:
linear_reg.intercept_

array([656046.53900487])

In [17]:
# predicting for 3000 sqft, 3 bedroom 40 year old
linear_reg.predict([[3000, 3, 40]])

array([[330999.05823262]])

In [18]:
# predicting for 2500 sqft, 4 bedroom 5 year old
linear_reg.predict([[2500, 4, 5]])

array([[614551.67948517]])

In [22]:
linear_reg.coef_[0][0]*3000+linear_reg.coef_[0][1]*3+linear_reg.coef_[0][2]*40+linear_reg.intercept_

array([330999.05823262])

In [23]:
linear_reg.coef_[0][0]*2500+linear_reg.coef_[0][1]*4+linear_reg.coef_[0][2]*5+linear_reg.intercept_

array([614551.67948517])